package com.fiap.hackathon.complains.entity;

import java.io.Serializable;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fiap.hackathon.complains.dto.NovaComplainDTO;

@DynamoDBTable(tableName ="complains")
public class Complains implements Serializable{

	private static final long serialVersionUID = 1L;
	
	private String id;
	private Date dataCriacao;
	private Date dataAlteracao;
	private String usuario;
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public Date getDataCriacao() {
		return dataCriacao;
	}
	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}
	
	@DynamoDBAttribute
	public Date getDataAlteracao() {
		return dataAlteracao;
	}
	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}
	
	@DynamoDBAttribute
	public String getUsuario() {
		return usuario;
	}
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Complains(String id, Date date, Date date2, String usuario) {
		super();
		this.id = id;
		this.dataCriacao = date;
		this.dataAlteracao = date2;
		this.usuario = usuario;
	}

	public Complains(NovaComplainDTO novaComplainDTO) {
	}

}
